### ISSUE TITLE
1.15.2 checksum error and validating with New Relic signature?

### ISSUE THREAD

**Issue by jeremygaither** [ripclawffb/chocolatey-newrelic-infra#1]
While attempting to install v1.15.2, we receive a checksum mismatch error:

![85E12350-6965-47A0-9BC4-4694EF5DDF67](https://user-images.githubusercontent.com/8432406/112509279-51939200-8d5e-11eb-9238-8ec86bfea3ae.jpeg)

Downloading the 1.15.2 installer from <https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.1.15.2.msi> has the following sha256 hash:

`c044b3601bb08cd2dcb318194c4b087303ed8d59ba7e35755f560066d523cf1b`

This does not match the hash in this package published on chocolatey.org:

```powershell
  checksum64     = '4a1398a71f848b9fd72b9f3207c0fd502551ff16dacac54776a39ca73754ab59'
  checksumType64 = 'sha256'
```

From the following source, it appears this issue is known:  https://github.com/ripclawffb/chocolatey-newrelic-infra/blob/cebde3e53e76f77a29fcec429e7d01161a7795c2/tools/chocolateyinstall.ps1#L48

https://chocolatey.org/packages/newrelic-infra/1.15.2.20210311 is still in moderation due to some failing tests.

I'm curious if the bits of the installer did change, and if there is a way we can check file shasum matches published and signed shasum anywhere. New Relic has some GPG keys and some info for checking the signature of other packages (eg the .net agent). Do you (or anyone) know of such a signature validation mechanism for the infrastructure agent?

**Comment by jeremygaither** [comment]
FYI @bhardister

**Comment by ripclawffb** [comment]
I've seen this occur in the past when NewRelic replaces their package with the same version number for one reason or another. That's why I created version 1.15.2.20210311. However, I think Chocolatey is having issues with their verification system because the package fails automated testing even though it works in my CI environment.

Even though the package is under moderation, you can still install it if you provide the explicit version number (1.15.2.20210311). 

Let me know if you still have issues.
